### Import Module

In [1]:
import numpy as np
np.random.seed(42)  # For reproducibility

##### 1D Arrays - Vectors

In [2]:
# 1D arrays are a collecttion of elements - also knows as vectors
ar_1d = np.array([1,2,3,4,5])

print(f"This array is {ar_1d} with a shape {ar_1d.shape} and dimension {ar_1d.ndim}.")

This array is [1 2 3 4 5] with a shape (5,) and dimension 1.


##### 2D Arrays - Matrix

In [3]:
# 2D arrays are 1D arrays (also vectors) stacked one below another
ar_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(f"This array is \n{ar_2d}\n with a shape {ar_2d.shape} and dimension {ar_2d.ndim}.")

This array is 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
 with a shape (2, 5) and dimension 2.


##### 3D Arrays - Stack of Matrices

In [4]:
# 3D arrays are 2D arrays stacked one on top of another
# similarily 4D arrays are 3D arrays stacked one beside another\

ar_3d = np.array(
	[
		[
			[1,2,3,4,5],
			[6,7,8,9,10]
		],
		[
			[11,12,13,14,15],
			[16,17,18,19,20]
		],
		[
			[21,22,23,24,25],
			[26,27,28,292,30]
		]
	]
)

print(f"This array is \n{ar_3d} \n with a shape {ar_3d.shape} and dimension {ar_3d.ndim}.")

This array is 
[[[  1   2   3   4   5]
  [  6   7   8   9  10]]

 [[ 11  12  13  14  15]
  [ 16  17  18  19  20]]

 [[ 21  22  23  24  25]
  [ 26  27  28 292  30]]] 
 with a shape (3, 2, 5) and dimension 3.


#### Array Properties

##### 1.Shape of an Array

In [5]:
# returns shape of an array
print(ar_1d.shape)
print(ar_2d.shape)
print(ar_3d.shape)

(5,)
(2, 5)
(3, 2, 5)


##### 2. Dimension of an Array

In [6]:
# returns dimension of an array
print(ar_1d.ndim)
print(ar_2d.ndim)
print(ar_3d.ndim)

1
2
3


##### 3.Size of an Array

In [7]:
# returns sizee of an array
print(ar_1d.size)
print(ar_2d.size)
print(ar_3d.size)

5
10
30


##### 4.Data Type of an Array

In [8]:
# returns data type of an array
print(ar_1d.dtype)
print(ar_2d.dtype)
print(ar_3d.dtype)

int64
int64
int64


##### 5.Memory Shape of an Array

In [9]:
print(ar_1d.itemsize)
print(ar_2d.itemsize)
print(ar_3d.itemsize)

8
8
8


#### Array Creation Methods

##### 1. Array of Zeroes

In [10]:
# takes shape as an argument
# by default returns the array in floating numbers
# if you want can specify the dtype as a seperate argument

# 1D array
print("1D Array")
print(np.zeros((10)),"\n")

# 2D array
print("2D Array")
print(np.zeros((2,3)),"\n")

# 3D array
print("3D Array")
print(np.zeros((3,3,6), dtype='int'),"\n")

# can go upto as many dimensions as we want

1D Array
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

2D Array
[[0. 0. 0.]
 [0. 0. 0.]] 

3D Array
[[[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]] 



##### 2. Array of Ones

In [11]:
# takes shape as an argument
# by default returns the array in floating numbers
# if you want can specify the dtype as a seperate argument

# 1D array
print("1D Array")
print(np.ones((10)),"\n")

# 2D array
print("2D Array")
print(np.ones((2,3)),"\n")

# 3D array
print("3D Array")
print(np.ones((3,3,6), dtype='int'),"\n")

# can go upto as many dimensions as we want

1D Array
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

2D Array
[[1. 1. 1.]
 [1. 1. 1.]] 

3D Array
[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]] 



##### 3. Array of a single number

In [12]:
# takes shape as an argument
# by default returns the array in integers
# if you want can specify the dtype as a seperate argument

# 1D array
print("1D Array")
print(np.full((10),10),"\n")

# 2D array
print("2D Array")
print(np.full((2,3),10),"\n")

# 3D array
print("3D Array")
print(np.full((3,3,6),10, dtype='float'),"\n")

# can go upto as many dimensions as we want

1D Array
[10 10 10 10 10 10 10 10 10 10] 

2D Array
[[10 10 10]
 [10 10 10]] 

3D Array
[[[10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10.]]

 [[10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10.]]

 [[10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10.]
  [10. 10. 10. 10. 10. 10.]]] 



##### 4. Creating array having the same shape as another array

* np.zeros_like() - Creates an array of zeros where the shape is of another array
* np.ones_like() - Creates an array of ones where the shape is of another array
* np.full_like() - Creates an array of numbers (same numbers) where the shape is of another array

In [13]:
# need to specify the array_name that we want the shape of

# 1D array
print("1D Array")
print(np.zeros_like(ar_1d),"\n")

# 2D array
print("2D Array")
print(np.ones_like(ar_2d, dtype='int'),"\n")

# 3D array
print("3D Array")
print(np.full_like(ar_3d,25,dtype='float'),"\n")

1D Array
[0 0 0 0 0] 

2D Array
[[1 1 1 1 1]
 [1 1 1 1 1]] 

3D Array
[[[25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]

 [[25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]

 [[25. 25. 25. 25. 25.]
  [25. 25. 25. 25. 25.]]] 



##### 5. Creating a identity Matrix 
A identity matrix is a matrix where the diagonal elements are 1 and the rest of the elements are 0.

In [15]:
# np.eye(n=,M=, k=0, dtype=)
	# n = number of rows
	# M = number of columns
	# k = Where do you want the diagonal to start
	# by default it returns a square matrix is M is not specified

print(np.eye(4),"\n")
print(np.eye(4,10),"\n")
print(np.eye(4,10,+2),"\n")
print(np.eye(8,10,-2),"\n")


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]] 

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]] 



In [16]:
# np.idenity also creates a identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### 6. Creating evenly spaced arrays 
Use np.linspace(start, stop, interval, dtype)

In [21]:
# np.arange(start =, stop = , interval = , dtype =)
# Returns only 1D array
# In case you need a multi-dimensional array use np.arange().reshape()
# In case only one number is mentioned np.arange(5) it considers it to be the stop value and 0 to be the start value
# In case you want to count backward, start >stop and step should be negative

print(np.arange(3,15,3),"\n")

print(np.arange(0,-15,-3),"\n")

print(np.arange(20),"\n")

print(np.arange(88,35,-8),"\n")

# using np.arange().reshape() to generate a multi-dimensional array
print(np.arange(88,25,-8).reshape(2,4),"\n")

[ 3  6  9 12] 

[  0  -3  -6  -9 -12] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

[88 80 72 64 56 48 40] 

[[88 80 72 64]
 [56 48 40 32]] 



##### 7. Creating evenly spaced arrays over a specified interval
Use np.linspace(start=,stop=,num=,endpoint=,retstep=,dtype=)

* start = start of the sequence
* stop = stop value of the sequence
* num = number of samples - by default it it 50
* endpoint = True/False (boolean) - if True it ends at the stop value if False then the stop value is excluded
* retstep - Step used to create the matrix

***
**Difference between np.arrange() and np.linspace() is**

using np.linspace()
- we can specify how many samples we want - by defualt 50 samples
- we can end the array at the stop value if we want

using np.arange()
- we can specify the step size we want 



In [22]:

#Endpoint =True - stops ar 50/last value will be 50 included
print(np.linspace(20,50,endpoint=True,num=30, dtype='int'))

#Endpoint =False hence stops at 49 and num not specified hence 50 samples by default
print(np.linspace(20,50,endpoint=False, dtype='int'))

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 50]
[20 20 21 21 22 23 23 24 24 25 26 26 27 27 28 29 29 30 30 31 32 32 33 33
 34 35 35 36 36 37 38 38 39 39 40 41 41 42 42 43 44 44 45 45 46 47 47 48
 48 49]


#### Array Operations 
##### Slicing and Extraction

In [ ]:
# slicing and extraction from arrays
# start from the outer layer and work your way inside


display(ar_3d)
print("\n")

#extract the second element
print(f"The second element is \n{ar_3d[1,:,:]}")
print("\n")

#extract the third element - can use -1 as last index starts from -1
print(f"The second element is \n{ar_3d[-1,:,:]}")
print("\n")

# extract row 2 of second element and columns 3 and 4
print(f"The items in the second row and columns 3 and 4 of the second element are {ar_3d[1,1,2:-1]}")
print("\n")

# using a step method to extract 
# extract the first third and fifth columns from the third element
print(f"The first, third and fifth columns and all rows from the third element are \n{ar_3d[-1,:,::2]}")


#### Array Operations
##### Changing elements 

In [ ]:
# change elements of an array using slicing

#before imputation
print(f"The original array before change was \n{ar_3d}")
print("\n")
# extraction 
ar_3d[-1,:,::2] = np.array([[41,44,47],[61,64,67]])
print(f"The original array after change was \n{ar_3d}")



#### Array Operations
##### Boolean Indexing

In [23]:
np.random.seed(42)
# 1D Array
array_1D = np.random.randint(30,100,20)
print(array_1D,"\n")
print("\n")

print("Print all elements which are greater than 50")
print(array_1D[array_1D>50])
print("\n")

print("Print the element 89")
print(array_1D[array_1D == 89])
print("\n")

print("Print the numbers between 45 and 75") 
print(array_1D[(array_1D>=45) & (array_1D<=75)])
print("\n")

print("Print the numbers less than 40 or greater than 80") 
print(array_1D[(array_1D <=40) | (array_1D >= 80)])
print("\n")

print("Print the numbers not less than 40 ") 
print(array_1D[~(array_1D <=40)])
print("\n")

[81 44 90 50 53 32 51 82 31 59 67 31 93 89 50 62 87 51 78 88] 



Print all elements which are greater than 50
[81 90 53 51 82 59 67 93 89 62 87 51 78 88]


Print the element 89
[89]


Print the numbers between 45 and 75
[50 53 51 59 67 50 62 51]


Print the numbers less than 40 or greater than 80
[81 90 32 82 31 31 93 89 87 88]


Print the numbers not less than 40 
[81 44 90 50 53 51 82 59 67 93 89 50 62 87 51 78 88]




In [31]:
np.random.seed(42)
# 2D Array
array_2D = np.random.randint(30,100,(4,5))
print(array_2D,"\n")
print("\n")

print("Print the element that are greater than 50")
print(array_2D[array_2D>50]) #returns a 1D array
print("\n")

print("Print the element that are greater than 50 but less than 75")
print(array_2D[(array_2D>50) & (array_2D<=75)]) #returns a 1D array
print("\n")

# By default boolean indexing occurs row-wise for Numpy
print("Print the rows where the third column elements are greater than 50 but less than 75")
print(array_2D[array_2D[:,2]>85]) #returns all the rows that has column 3 values gt 60
print("\n")

print("Print the rows where the third column elements are greater than 85 and less than 80")
print(array_2D[(array_2D[:,2]>85) & (array_2D[:,0]<80)])
print("\n")


[[81 44 90 50 53]
 [32 51 82 31 59]
 [67 31 93 89 50]
 [62 87 51 78 88]] 



Print the element that are greater than 50
[81 90 53 51 82 59 67 93 89 62 87 51 78 88]


Print the element that are greater than 50 but less than 75
[53 51 59 67 62 51]


Print the rows where the third column elements are greater than 50 but less than 75
[[81 44 90 50 53]
 [67 31 93 89 50]]


Print the rows where the third column elements are greater than 85 and less than 80
[[67 31 93 89 50]]




#####  Fancy (List) Indexing

In [56]:
random_ar = np.random.randint(100,150,(6,6))

print(random_ar)
print("\n")

#Indexing using a list
# Specific Row indexing
print("Take out row 1 and row 3 with all the columns")
print(random_ar[[1,3]])
print("\n")

# Specific column indexing
print("Take out row 1 and row 3 with all the columns")
print(random_ar[:,[1,3]])
print("\n")

#Selecting individual elements - pairwise indexing
	# (4,1),(5,3) elements will be picked up from the array
print(random_ar[[4,5],[1,3]])



[[128 102 119 135 118 125]
 [102 118 119 131 106 140]
 [132 139 138 117 139 100]
 [110 127 124 149 122 130]
 [129 141 134 106 115 125]
 [147 148 101 100 147 111]]


Take out row 1 and row 3 with all the columns
[[102 118 119 131 106 140]
 [110 127 124 149 122 130]]


Take out row 1 and row 3 with all the columns
[[102 135]
 [118 131]
 [139 117]
 [127 149]
 [141 106]
 [148 100]]


[141 100]


### Array Generation - Random Module

##### 1. np.random.rand()

Create an array of random floating numbers between [0,1) 

In [ ]:
# generate a array of random floating point numbers between 0 and 1
# including 0 but excuding 1
# use np.random.rand()
# shape is not put in as an argument seperately

# 1D Array
print("1D Array")
print(np.random.rand(5))
print("\n")

# 2D Array
print("2D Array")
print(np.random.rand(2,4))
print("\n")

# 3D Array
print("3D Array")
print(np.random.rand(2,3,3))
print("\n")

In [ ]:
# 4D Array
print("4D Array")
print(np.random.rand(2,3,3,3))
print("\n")



##### 2. np.random.randint()
Create an array of random real numbers of desired size with a low and high value

In [ ]:
# 1D Array
print("1D Array")
print(np.random.randint(10,12, size =(5)))
print("\n")

# 2D Array
print("2D Array")
print(np.random.randint(10,30, size = (3,7)))
print("\n")

# 3D Array
print("3D Array")
print(np.random.randint(30, 50, size= (2,3,3)))
print("\n")

##### 3.np.random.randn()
Create an array of random numbers between -3 and 3 that follows a standard normal distribution

np.random.standard_normal() can also be used to generate values from a standard normal distribution but takes size as an argument instead of shape

In [ ]:
# randn() provides values that form an standard normal distribution
# np.random.standard_normal() can also be used to generate values from a standard normal distribution but takes size as an argument instead of shape
# 1D Array
print("1D Array")
print(np.random.randn(5))
print("\n")

# 2D Array
print("2D Array")
print(np.random.randn(2,4))
print("\n")

# 3D Array
print("3D Array")
print(np.random.randn(2,3,3))
print("\n")

In [ ]:
import seaborn as sns
sns.kdeplot(np.random.randn(1000), fill=True)

##### 4.np.random.normal()
Create an array of random numbers taken from a normal distribution if mean "loc" and sd "scale"

In [ ]:
# Creates an array of numbers that are normally distributed 
	# loc = mean
	# scale = sd
	# size = desired array size

normal_dist_array = np.random.normal(loc =5, scale =1,size =(2,3))

# this is useful while using real world data where you have millions of rows as data and 5 numerical features for the model
# You want to compare the deviation of the actual distribution with mean mu and sd sigma vs a perfectly normal distribution of same stats

In [ ]:
#plotting a normal distribution

sns.kdeplot(np.random.normal(38,1,size =(10000,6)))

### Linear Algebra Operations 

##### 1. Rank of a Matrix

In [ ]:
a = np.random.randint(20,40,size = (3,5))
print(a)
print("\n")

# inititalize a square matrix
sq_matrix = np.random.randint(10,50, size = (4,4))

# rank of a matrix - no of linearly independent rows or columns of a matrix
	# if a row or column is formed by addition subtraction multiplication of one or more rows of the matrix - then that row is linearly dependent
	# the rank can never be larger than the smallest dimension of your matrix
		# For a (3 rows, 5 columns), the maximum possible rank is 3.

#linearly independent matrix
print(f"Rank of a Matrix \n{a}\n is")
print(np.linalg.matrix_rank(a))
print("which shows it is linearly independent")
print("\n")

#linearly dependent matrix
print(f"Rank of a Matrix \n{np.array([[1,2,3,4],[4,8,12,16]])}\n is")
print(np.linalg.matrix_rank(np.array([[1,2,3,4],[4,8,12,16]])))
print("which shows it is not linearly independent")
print("\n")

##### 2. Power of a Matrix - only for a square matrix

In [ ]:
display(sq_matrix)

# power of a matrix - occurs only for a square matrix - multiplies the matrix several times raised to the power n
print("Power of a matrix")
print(np.linalg.matrix_power(sq_matrix,3))
print("\n")



##### 3. Deteminant of a Matrix - only for a square matrix

**Basis Vectors**

A basis vector is a vector which you can use to span every point or vector in the space that has them. Basically you can go to any desired scalar or vector coordinate space with the help of those vectors. 

#### Unit Vectors in Different Dimensions

##### In 2D Space (R^2 space)

The standard unit vectors in 2-dimensional space are
- i = [1,0]
- j = [0,1]

These are unit vectors or basis vectors and they span the entire 2D space R^2
These represent the unit vectors along the **x-axis** and **y-axis** respectively.


#### In 3D Space (R^3 space)

The standard unit vectors in 3-dimensional space are:
- i = [1,0,0]
- j = [0,1,0]
- k = [0,0,1]

Here, *k* vector is added to represent the unit vector along the **z-axis**.
These are unit vectors or basis vectors and they span the entire 2D space R^3

---

**What is determinant actually?**

For a standard 2D matrix the determinant is basically the area of the parallelogram that is created when you apply the matrix transformation i.e., a linear transformation on the basis vectors i and j. This transformation changes or stretches the entire 2D space, not specifically the a particular point or co-ordinate space. 

In case of a 2D space,  i = [1,0] and j = [0,1]. 

- Imagine this to be a unit square on a 2D grid at the origin where the sides of the square represents the unit basis vectors. Using this you can go to any point within the 2D grid. 
- Now, suppose you apply a matrix transformation to the entire grid. Imagine pulling this from a side so that all the gridlines are now stretched to a particular direction but all are still straight lines and parallel to each others. 
- The matrix moves the basis vectors i and j to new positions, turning our perfect grid into a slanted, stretched grid. 
- The original 1 X 1 square is now a skewed parallelogram.
- The Determinant is the area of that new parallelogram.

* In 2D: The determinant is the area of the transformed unit square (parallelogram).
* In 3D: The determinant is the volume of the transformed unit cube (parallelepiped).
* In Higher Dimensions ($nD$): It is the factor by which the "$n$-dimensional volume" changes.

***
If determinant of a matrix is +6 no matter what the shape of the matrix is, it will always scale the area by a factor of +6
This means that if you pass a (2,3) matrix or a (7,9) matrix if the determinant is 6 then both of those matrix transformations will scale the area of the parallelogram created by the basis vectors by +6 or a factor of +6

Two matrices can have completely different entries, pull space in different directions, and create entirely different looking shapes. 
But if their determinants are equal, the total amount of space they "create" or expand is exactly the same.
***

In [ ]:
display(sq_matrix)
# determinant of a matrix - occurs only for a square matrix - multiplies the matrix several times raised to the power n
print("The determinant is")
print(np.linalg.det(sq_matrix))

##### 4. Transpose of a Matrix

In [ ]:
display(a)

print("The transpose of the matrix is")
print(np.linalg.matrix_transpose(a))

print(f'''The shape of the matrix is {np.linalg.matrix_transpose(a).shape} and dimension is {np.linalg.matrix_transpose(a).ndim}''')

##### 4. Eigen Values and Eigen Vectors - only for a square matrix

| Function | Matrix Type | What it Returns | Speed / Stability |
| :--- | :--- | :--- | :--- |
| **np.linalg.eig** | General Square | Eigenvalues + Eigenvectors | Standard |
| **np.linalg.eigvals** | General Square | Eigenvalues only | Faster (skips vectors) |
| **np.linalg.eigh** | Symmetric / Hermitian | Eigenvalues + Eigenvectors | Fastest & Most Stable |
| **np.linalg.eigvalsh** | Symmetric / Hermitian | Eigenvalues only | Blazing Fast |

1. If A = AT then it is a symmetric matrix comprising of real numbers

2. A matrix is Hermitian if it equals its own conjugate transpose ($A = A^H$). This means you flip the rows and columns and change the sign of the imaginary parts (e.g., $2 + 3i$ becomes $2 - 3i$). The diagonal has to be a real number though for this matrix.

In [ ]:
print(sq_matrix)
print("\n")

eigenvalues, eigenvectors = np.linalg.eig(sq_matrix)

# eigen values
print("Eigenvalues: ", eigenvalues)
print("\n")

# eigen vectors
print("Eigenvectors: ", eigenvectors)


##### 4. Inverse of a matrix - only for a square matrix

In [ ]:
# inverse calculation only occurs for square matrix as the determinant needs to be calculated

np.linalg.inv(sq_matrix)

### A universal, ironclad law in linear algebra is that for every single square matrix, the determinant is exactly equal to the product of its eigenvalues.

##### 5. Condition Number of a Matrix

***
The condition number measures how sensitive a system of linear equations Ax=B (imagine linear regression) is to small changes or numerical rounding errors. Basically assess the numerical stability.
- If the condition number is low then it is good, small changes in the data does not change the output by much - close to 1 is good as there sis computation statbility.
- If the condition number is high then it is a ill-conditioned matrix, small changes or tweaks in the data can change the output by large amounts - very high is not good.
- If the condition number is infinite then the matrix is singular (determinant is 0) -  the 2D space has flattened to a 1D line post that matrix transformation - matrix is singular and has linearly dependent rows or columns

***
In data science, 
* the condition number tells you how sensitive a linear regression model's outputs (the coefficient weights) are to small changes in the inputs (the feature data). 
* A very high condition number means your matrix (XT X)^^-1 part of the beta matrix is close to becoming singular (determinant near 0), indicating severe multicollinearity.
* Infinite condition Number tells that the matrix has linearly dependent rows and columns and suffer from perfect multicollinearity.

In predictive modeling and regression, a very high condition number is an immediate red flag for severe multicollinearity (independent variables are highly correlated), 
meaning your model's coefficients are highly unstable as they suffer from high standard deviations even though the estimates are unbiased. 

***
**Condition Number = ||A||.||A^-1||**
or, **Condition Number = max(singular values)/ min(singular values)**

Here ||A|| is called the norm of the matrix. By default numpy uses the spectral/2D norm of the matrix (np.linalg.matrix_norm())
One common norm is also the Frobenius norm which is the sqrt(sum of square of matrix elements) - (np.linalg.matrix_norm(array,'fro'))

Using the spectral norm we,
* perfrom singular value decomposition on the matrix
* calculate the maximum and minimum singular values
* calcualte Condition Number using their ratio

***
* If you have your data matrix of mXn shape then use **Ratio of largest to smallest singular value**.
* If you have the scaled version of covariance matrix (square matrix) then use **sqrt(Ratio of largest to smallest eigen value)** 

In [ ]:
np.random.seed(42) #for reproducibility
r1 = np.random.randint(50,80,(3,6))
print(f"Condition number of the matrix \n{r1}\n is {np.linalg.cond(r1)}")

##### 6. Diagonal Extraction

In [ ]:
# np.diagonal() or np.linalg.diagpnal() extracts the diagonal elements of a 2D array
# For a array of higer dimension it isolates the batch dimensions A[i,j] and then return the diagonal elements of each batch dimension stacked in an array
# for a 2D array we can also use np.diag() which also extracts the elements\

print(sq_matrix)
print("\n")

print(f"The array of diagonal elements are {np.diagonal(sq_matrix)}")

In [ ]:
# A 3D array representing a batch of TWO 2x2 matrices
# Shape: (2, 2, 2) -> (batch, rows, columns)
matrix_stack = np.array([
    [[1, 2],
     [3, 4]],  # Matrix 1 (Diagonal is [1, 4])
     
    [[5, 6],
     [7, 8]]   # Matrix 2 (Diagonal is [5, 8])
])

np.linalg.diagonal(matrix_stack)



##### 7. Create a Diagonal Matrix

In [ ]:
# np.diag() creates a diagonal matrix when a 1D array is passed
# for a 2D array it extracts the diagonal elements

print(sq_matrix)
print("\n")

print("The diagonal matrix is","\n")
print(np.diag(np.diagonal(sq_matrix)))

##### Appending one array to another 
Works only if the two iput arrays are of the same shape

In [ ]:
array1 = np.random.randint(20,40,(2,3,4))
print(array1)
print("\n")

array2 = np.random.randint(50,100,(2,3,4))
print(array2)

array3= np.append(array1, array2, axis =0)
print(array3)


##### Absolute of an Array

In [ ]:

np.random.seed(42)
z = np.random.randn(3,4)

print(z)
print("\n")
np.absolute(z)